config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'pages#home'

  # resources :users do
    # resources :cocktails, only: [:index, :create]
  # end

  resources :cocktails, only: [:show, :new, :destroy, :index, :create] do
    resources :doses, only: [:create]
  end

  resources :doses, only: [:destroy]

  resources :ingredients, only: [:show]

  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  belongs_to :user

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: { message: "must be given please" }, uniqueness: { case_sensitive: false }

  mount_uploader :photo, PhotoUploader
  validates :photo, presence: { message: "must be given please" }
end

app/models/dose.rb
class Dose < ApplicationRecord

  belongs_to :ingredient
  belongs_to :cocktail
  has_attachment :photo_ingredient

  validates :description, presence: true, allow_blank: false
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient, message: "Should have one dose of a certain ingredient for a cocktail"}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: { message: "must be given please" }, uniqueness: { case_sensitive: false }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cocktails, dependent: :nullify

  devise :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  after_create :send_welcome_email

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      #user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def self.from_omniauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:google_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h
    # data = auth.info ...
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email:auth.info.email)
    unless user
        user = User.new(user_params)
        user.password = Devise.friendly_token[0,20]
        user.save
    end
    user
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :destroy]

  def index
    @cocktails = current_user.cocktails
  end

  def show
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.user = current_user
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache, :user_id)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :photo_ingredient)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: :home

  def home
    if user_signed_in?
      redirect_to cocktails_path(current_user)
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, "Let's create a cocktail !!", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class='banner'>
  <% avatar_url = current_user.google_picture_url || current_user.facebook_picture_url %>
  <% if avatar_url %>
    <%= image_tag avatar_url, class: 'avatar_profil_picture' %>
  <% end %>
  <h1 class="text-center">Your cocktail list</h1>
</div>
<div class="text-center padded" id="cocktail-creation-home">
  <%= link_to "Create a cocktail", new_cocktail_path, class: 'btn btn-success cocktail-creation-button' %>
</div>


<div class="container" style="margin-top: 17px;">
  <div class="row">

    <% @cocktails.each do |cocktail| %>

    <div class="col-xs-12 col-sm-4 banner-xs-cocktails">
      <%=  link_to cocktail_path(cocktail), class: 'show-card-link' do %>
          <div class="card flex-cocktail-card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.7)), url('<%= cocktail.photo? ? cl_image_path(cocktail.photo) : "https://unsplash.it/200/300" ; %>');" >

            <div class="cocktail-title">
              <h4 class="text-center"><%= cocktail.name %></h4>
            </div>

          </div>
      <% end %>
      </div>


    <% end %>

  </div>

  <div class='log_out'>
    <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
  </div>

</div>

app/views/cocktails/new.html.erb
<div class="container">


  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <h1>New Cocktail</h1>
      <%= render 'form', cocktail: @cocktail %>
      <%= link_to 'Back', cocktails_path %>

    </div>
  </div>

</div>

app/views/cocktails/show.html.erb
<div class="mobile-header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path @cocktail.photo.url(:cocktail_display) %>')">
  <h1><%= @cocktail.name %></h1>
</div>

<div class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-sm-offset-0" style="margin-bottom:25px">



      <div class="other-header text-center">
        <h1><%= @cocktail.name %></h1>
      </div>

      <div class="flex-display-cocktail">

        <ul class="list-unstyled boxing-list-ingredients">
          <% @cocktail.doses.each do |dose| %>
            <li>

              <%= cl_image_tag(dose.photo_ingredient.path, width: 40, height: 40, crop: :fill, class: "avatar-ingredient") if dose.photo_ingredient? %>
              <%= link_to "<i class='fa fa-close '></i>".html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }, class: 'text-danger' %>
              <%= link_to dose.ingredient.name, ingredient_path(dose.ingredient), class: "ingredient-name-list" %> : <%= dose.description.strip %>

            </li>
          <% end %>
        </ul>

        <div class="side-image-sm" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)),
         url('<%= cl_image_path @cocktail.photo.url(:cocktail_side_display) %>')">
        </div>

      </div>

      <div class="flex-arrow-down">
        <i class="fa fa-angle-down" aria-hidden="true"></i>
      </div>

      <hr />

      <div class="formulaire">
        <p>Please enter an ingredient with its associate dose and description:</p>

        <% if @dose.errors.any? %>
          <ul>
            <% @dose.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= simple_form_for([@cocktail, @dose]) do |f| %>

          <div class="grid">
            <%= f.association :ingredient , collection: @ingredients %>
            <%= f.input :photo_ingredient, as: :attachinary, label: false %>
          </div>
          <%= f.input :description %>
          <div class="text-center"><%= f.button :submit, class: "btn btn-primary create-dose-button" %></div>

        <% end %>

      </div>

      <hr />

      <div class="footer">
        <%= link_to 'Back', cocktails_path %>
        <%= link_to 'DESTROY', cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure you want to discard this cocktail ?"} %>
      </div>
    </div>
  </div>

</div>

app/views/ingredients/show.html.erb
<h1>Les cocktails avec du <%= @ingredient.name %> sont :</h1>

<ul>
  <% @ingredient.cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background_body" style="background-image:  url(' <%= cl_image_path("yqpjk47c78g7jxn1eitb.jpg") %> ');" >
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to 'sign up', new_user_registration_path %>

<%= link_to 'sign in', new_user_session_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>